[package]
name = "cookie-auth"
version = "2.0.0"
authors = ["Nikolay Kim <fafhrd91@gmail.com>"]
edition = "2018"

[dependencies]
ntex = { version = "0.5", features = ["tokio"] }
ntex-identity = "0.1"
env_logger = "0.9"
