[package]
name = "run-in-thread"
version = "2.0.0"
authors = ["Nikolay Kim <fafhrd91@gmail.com>"]
edition = "2018"
description = "Run actix-web in separate thread"

[dependencies]
ntex = { version = "0.5", features = ["tokio"] }
env_logger = "0.9"
