[package]
name = "juniper-example"
version = "0.2.0"
authors = ["pyros2097 <pyros2097@gmail.com>"]
edition = "2018"

[dependencies]
ntex = "0.3"
env_logger = "0.8"
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"
juniper = "0.14"
