[package]
name = "json_error"
version = "1.0.0"
authors = ["Kai Yao <kai.b.yao@gmail.com>"]
edition = "2018"

[dependencies]
ntex = "0.3"
futures = "0.3"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
