[package]
name = "basics"
version = "4.0.0"
authors = ["Nikolay Kim <fafhrd91@gmail.com>"]
edition = "2018"

[dependencies]
ntex = { version = "1.0.0-b.1", features = ["tokio"] }
ntex-files = "0.4.0-b.0"
ntex-session = "0.4.0-b.0"
futures = "0.3"
env_logger = "0.10"
