[package]
name = "static_index"
version = "4.0.0"
authors = ["Jose Marinez <digeratus@gmail.com>"]
edition = "2018"

[dependencies]
futures = "0.3"
env_logger = "0.10"

ntex = { version = "1.0", features = ["tokio"] }
ntex-files = "0.4"
