[package]
name = "websocket-chat"
version = "2.0.0"
authors = ["Nikolay Kim <fafhrd91@gmail.com>"]
edition = "2018"

[[bin]]
name = "websocket-chat-server"
path = "src/main.rs"

[dependencies]
ntex = "0.3"
ntex-files = "0.1"

rand = "0.8"
futures = "0.3"
env_logger = "0.8"
serde = "1.0"
serde_json = "1.0"
