[package]
name = "awc_https"
version = "0.3.0"
authors = ["dowwie <dkcdkg@gmail.com>"]
edition = "2018"

[dependencies]
ntex = { version = "1.0.0-b.1", features = ["openssl", "tokio"] }
openssl = "0.10"
