[package]
name = "cookie-session"
version = "1.0.0"
authors = ["Nikolay Kim <fafhrd91@gmail.com>"]
edition = "2018"

[dependencies]
ntex = { version = "0.5", features = ["tokio"] }
ntex-session = "0.1"
futures = "0.3"
time = "0.3"
env_logger = "0.9"
