[package]
name = "cookie-session"
version = "1.0.0"
authors = ["Nikolay Kim <fafhrd91@gmail.com>"]
edition = "2018"

[dependencies]
ntex = "0.3"
ntex-session = "0.1"
futures = "0.3"
time = "0.1"
env_logger = "0.8"
