[package]
name = "unix-socket"
version = "2.0.0"
authors = ["Messense Lv <messense@icloud.com>"]
edition = "2018"

[dependencies]
ntex = { version = "0.6.0-beta.0", features = ["tokio"] }
env_logger = "0.9"
